import {MAX_BYTES,MAX_ENTITIES,categories,inspectDrawing} from '../dist/cad-model.mjs';
const json=(data,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(status,message)=>{throw Object.assign(new Error(message),{status});};
const str=(value,max=200)=>{if(typeof value!=='string'||value.length>max)fail(400,'문자열 입력 범위를 확인하세요.');return value;};
const id=()=>crypto.randomUUID(),now=()=>new Date().toISOString();
function serialized(value,max=180000){const s=JSON.stringify(value);if(!s||s.length>max)fail(413,'객체 데이터가 허용 크기를 넘습니다.');const scan=(v,depth=0)=>{if(depth>25)fail(400,'객체 구조가 너무 깊습니다.');if(typeof v==='number'&&!Number.isFinite(v))fail(400,'유효하지 않은 숫자입니다.');if(v&&typeof v==='object')for(const [k,x] of Object.entries(v)){if(['__proto__','constructor','prototype'].includes(k))fail(400,'허용되지 않는 속성입니다.');scan(x,depth+1);}};scan(value);return s;}
function validateMetadata(m){if(!m||typeof m!=='object')fail(400,'도면 정보가 없습니다.');serialized(m,1000000);if(!Array.isArray(m.bays)||m.bays.length>100)fail(400,'Bay는 100개 이내로 등록하세요.');for(const b of m.bays){str(b.name,80);if(!['x','y','w','h'].every(k=>Number.isFinite(b[k]))||b.w<=0||b.h<=0)fail(400,'Bay 크기와 좌표가 올바르지 않습니다.');}if(!Array.isArray(m.groups)||m.groups.length>10000)fail(400,'BOX 그룹 정보를 확인하세요.');const members=new Set(),groupIds=new Set();for(const g of m.groups){str(g.id,100);str(g.name,100);if(groupIds.has(g.id)||!Array.isArray(g.memberIds)||g.memberIds.length<2||g.memberIds.length>10000)fail(400,'BOX 그룹 구성원을 확인하세요.');groupIds.add(g.id);for(const id of g.memberIds){str(id,120);if(members.has(id))fail(400,'BOX 그룹의 중복 객체입니다.');members.add(id);}}for(const b of m.bays){if(b.serviceWidth!==undefined&&(!Number.isFinite(b.serviceWidth)||b.serviceWidth<0||b.serviceWidth>=(['top','bottom'].includes(b.serviceSide)?b.h:b.w)))fail(400,'인프라 구역 폭은 Bay보다 작아야 합니다.');if(b.serviceSide&&!['left','right','top','bottom'].includes(b.serviceSide))fail(400,'인프라 구역 방향을 확인하세요.');}if(!Number.isFinite(m.clearance)||m.clearance<0)fail(400,'이격거리를 확인하세요.');if(!Number.isInteger(m.expectedBoxes)||m.expectedBoxes<0||m.expectedBoxes>MAX_ENTITIES)fail(400,'예상 BOX 수를 확인하세요.');if(![0,1,2,4,5,6].includes(m.units))fail(400,'지원하는 단위를 선택하세요.');if(m.codeLinks!==undefined&&(!Array.isArray(m.codeLinks)||m.codeLinks.length>10000||m.codeLinks.some(l=>typeof l.boxId!=='string'||typeof l.entityId!=='string')))fail(400,'코드 문자 연결을 확인하세요.');if(m.repairSettings){const r=m.repairSettings;if(!Number.isFinite(r.tolerance)||r.tolerance<0||!Number.isFinite(r.searchDistance)||r.searchDistance<0||typeof r.aliases!=='string'||r.aliases.length>1000)fail(400,'BOX 정리 기준을 확인하세요.');}for(const role of Object.values(m.layerMap||{}))if(!categories[role])fail(400,'레이어 분류를 확인하세요.');return m;}
function validateEntity(data){serialized(data);if(!data||typeof data!=='object'||Array.isArray(data))fail(400,'객체 데이터를 확인하세요.');if(data._placement&&!['x','y'].every(k=>Number.isFinite(data._placement[k])&&Math.abs(data._placement[k])<1e12))fail(400,'위치 이동량을 확인하세요.');if(data._constructionCode!==undefined&&(typeof data._constructionCode!=='string'||data._constructionCode.length>80))fail(400,'건설코드는 80자 이내 문자열이어야 합니다.');if(data._locked!==undefined&&typeof data._locked!=='boolean')fail(400,'위치 고정 값을 확인하세요.');}
const record=r=>({...r,data:JSON.parse(r.data),original:undefined});
async function owned(db,drawingId,owner){const d=await db.prepare('SELECT * FROM drawings WHERE id=? AND owner=?').bind(drawingId,owner).first();if(!d)fail(404,'도면을 찾을 수 없습니다.');return {...d,metadata:JSON.parse(d.metadata)};}
async function allRecords(db,d){return (await db.prepare('SELECT * FROM entities WHERE drawing_id=? ORDER BY ordinal').bind(d.id).all()).results.map(record);}
async function bodyJSON(req,max=2000000){if(Number(req.headers.get('content-length'))>max)fail(413,'요청이 너무 큽니다.');const text=await req.text();if(text.length>max)fail(413,'요청이 너무 큽니다.');try{return JSON.parse(text);}catch{fail(400,'JSON 형식이 올바르지 않습니다.');}}
export default {async fetch(request,env){
 const url=new URL(request.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS?env.ASSETS.fetch(request):new Response('Not found',{status:404});
 try{
  const owner=request.headers.get('oai-authenticated-user-id');if(!owner)fail(401,'로그인 후 도면 DB를 사용할 수 있습니다.');
  if(!['GET','HEAD'].includes(request.method)&&request.headers.get('origin')&&request.headers.get('origin')!==url.origin)fail(403,'다른 사이트에서의 저장 요청은 허용하지 않습니다.');
  if(!env.DB||!env.BUCKET)fail(503,'도면 저장소 연결을 확인하고 다시 시도하세요.');const db=env.DB;
  if(url.pathname==='/api/drawings'&&request.method==='GET')return json({drawings:(await db.prepare('SELECT id,name,size,status,expected,revision,reviewed_revision,created_at,updated_at FROM drawings WHERE owner=? ORDER BY updated_at DESC LIMIT 100').bind(owner).all()).results});
  if(url.pathname==='/api/drawings'&&request.method==='POST'){
   if(Number(request.headers.get('content-length'))>MAX_BYTES+2000000)fail(413,'DWG 최대 크기는 20 MB입니다.');let form;try{form=await request.formData();}catch{fail(400,'파일 업로드 형식이 올바르지 않습니다.');}const file=form.get('file');if(!file||typeof file.arrayBuffer!=='function'||!file.name.toLowerCase().endsWith('.dwg')||file.size>MAX_BYTES||file.size<6)fail(400,'20 MB 이하 DWG 파일을 선택하세요.');
   let manifest;try{manifest=JSON.parse(form.get('manifest'));}catch{fail(400,'추출 정보를 확인하세요.');}validateMetadata(manifest.metadata);if(!Number.isInteger(manifest.count)||manifest.count<1||manifest.count>MAX_ENTITIES)fail(400,'객체 수가 허용 범위를 벗어납니다.');
   const bytes=await file.arrayBuffer(),signature=new TextDecoder().decode(bytes.slice(0,6));if(!/^AC10\d\d$/.test(signature))fail(400,'DWG 파일 서명이 올바르지 않습니다.');const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');const drawingId=id(),time=now(),key=`${owner}/${drawingId}/original.dwg`;
   await env.BUCKET.put(key,bytes,{httpMetadata:{contentType:'application/acad'}});
   try{await db.prepare('INSERT INTO drawings (id,owner,name,sha256,size,status,metadata,expected,revision,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(drawingId,owner,str(file.name,240),hash,file.size,'importing',serialized(manifest.metadata,1000000),manifest.count,1,time,time).run();}catch(error){await env.BUCKET.delete(key);throw error;}
   return json({id:drawingId,revision:1},201);
  }
  const route=url.pathname.match(/^\/api\/drawings\/([0-9a-f-]+)(?:\/(entities|finish|change|review|history|original|source))?$/);if(!route)fail(404,'없는 API입니다.');const d=await owned(db,route[1],owner),op=route[2];
  if(!op&&request.method==='GET')return json({drawing:d});
  if(op==='original'&&request.method==='GET'){const object=await env.BUCKET.get(`${owner}/${d.id}/original.dwg`);if(!object)fail(404,'원본 파일을 찾을 수 없습니다.');return new Response(object.body,{headers:{'Content-Type':'application/acad','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(d.name)}`,'Cache-Control':'no-store'}});}
  if(op==='entities'&&request.method==='GET'){const offset=Number(url.searchParams.get('offset')||0);if(!Number.isInteger(offset)||offset<0)fail(400,'잘못된 페이지입니다.');const rows=(await db.prepare('SELECT * FROM entities WHERE drawing_id=? ORDER BY ordinal LIMIT 500 OFFSET ?').bind(d.id,offset).all()).results;return json({entities:rows.map(record),next:rows.length===500?offset+500:null});}
  if(op==='source'&&request.method==='GET'){const row=await db.prepare('SELECT original FROM entities WHERE drawing_id=? AND id=?').bind(d.id,url.searchParams.get('entity')).first();if(!row)fail(404,'객체가 없습니다.');return json({original:JSON.parse(row.original)});}
  if(op==='history'&&request.method==='GET')return json({edits:(await db.prepare('SELECT id,entity_id,reason,before_data,after_data,created_at FROM edits WHERE drawing_id=? ORDER BY created_at DESC LIMIT 100').bind(d.id).all()).results});
  if(op==='entities'&&request.method==='POST'){
   if(d.status!=='importing')fail(409,'이미 DB 추출을 마친 도면입니다.');const b=await bodyJSON(request);if(!Array.isArray(b.records)||!b.records.length||b.records.length>100||!Number.isInteger(b.offset)||b.offset<0||b.offset+b.records.length>d.expected)fail(400,'객체 묶음 범위를 확인하세요.');
   const statements=b.records.map((r,i)=>{validateEntity(r.data);const raw=serialized(r.data);if(!r.data||typeof r.data!=='object'||r.data.type!==r.type||!categories[r.classification])fail(400,'객체 형식이 올바르지 않습니다.');return db.prepare("INSERT INTO entities (id,drawing_id,ordinal,handle,type,space,layer,original,data,classification,notes,version) SELECT ?,?,?,?,?,?,?,?,?,?,?,1 WHERE EXISTS (SELECT 1 FROM drawings WHERE id=? AND owner=? AND status='importing') ON CONFLICT(drawing_id,ordinal) DO NOTHING").bind(`${d.id}-${b.offset+i}`,d.id,b.offset+i,str(r.handle,200),str(r.type,100),str(r.space,300),str(r.layer,300),raw,raw,r.classification,'',d.id,owner);});await db.batch(statements);return json({accepted:b.records.length});
  }
  if(op==='finish'&&request.method==='POST'){
   if(d.status!=='importing')return json({status:d.status});const total=await db.prepare('SELECT COUNT(*) AS count, SUM(length(data)) AS bytes FROM entities WHERE drawing_id=?').bind(d.id).first();if(total.count!==d.expected)fail(409,'객체 업로드가 끝나지 않았습니다.');if(total.bytes>16000000)fail(413,'객체 DB 크기가 16 MB를 넘습니다. Bay별로 도면을 나눠주세요.');await db.prepare("UPDATE drawings SET status='ready',updated_at=? WHERE id=? AND owner=? AND status='importing'").bind(now(),d.id,owner).run();return json({status:'ready',count:total.count});
  }
  if(op==='change'&&request.method==='POST'){
   if(d.status!=='ready')fail(409,'추출 완료 후 편집할 수 있습니다.');const b=await bodyJSON(request,3000000);if(b.revision!==d.revision)fail(409,'다른 변경이 저장되었습니다. 새로 불러온 후 수정하세요.');const reason=str(b.reason,300).trim();if(!reason)fail(400,'변경 사유를 입력하세요.');const changes=b.changes||[];if(!Array.isArray(changes)||changes.length>100||new Set(changes.map(r=>r.id)).size!==changes.length)fail(400,'변경 묶음은 서로 다른 객체 100개 이내여야 합니다.');
   const metadata=b.metadata?validateMetadata(b.metadata):d.metadata;
   // Decoder provenance cannot be cleared through an edit or a forged review request.
   for(const key of ['readError','unknownEntityCount','version','parser','auditMissingCount','auditFailures','auditMissing'])metadata[key]=d.metadata[key];
   if(b.metadata&&metadata.groups.length){const ids=new Set((await db.prepare("SELECT id FROM entities WHERE drawing_id=? AND space='model'").bind(d.id).all()).results.map(r=>r.id));if(metadata.groups.some(g=>g.memberIds.some(id=>!ids.has(id))))fail(400,'BOX 그룹에 없는 모델 객체가 포함되어 있습니다.');}
   const statements=[],time=now();for(const r of changes){const old=await db.prepare('SELECT * FROM entities WHERE drawing_id=? AND id=?').bind(d.id,r.id).first();if(!old||old.version!==r.version)fail(409,'객체가 변경되었습니다. 새로 불러오세요.');if(r.data?.type!==old.type||r.data?.handle!==JSON.parse(old.original).handle)fail(400,'객체 종류와 원본 Handle은 변경할 수 없습니다.');if(!categories[r.classification])fail(400,'객체 분류를 확인하세요.');validateEntity(r.data);const layer=str(r.layer,300),notes=str(r.notes||'',2000);r.data.layer=layer;const finalData=serialized(r.data);
    statements.push(db.prepare('INSERT INTO edits (id,drawing_id,entity_id,owner,reason,before_data,after_data,created_at) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM drawings WHERE id=? AND owner=? AND revision=?)').bind(id(),d.id,r.id,owner,reason,serialized({data:JSON.parse(old.data),layer:old.layer,classification:old.classification,notes:old.notes},190000),serialized({data:r.data,layer,classification:r.classification,notes},190000),time,d.id,owner,d.revision));
    statements.push(db.prepare('UPDATE entities SET data=?,layer=?,classification=?,notes=?,version=version+1 WHERE id=? AND drawing_id=? AND version=? AND EXISTS (SELECT 1 FROM drawings WHERE id=? AND owner=? AND revision=?)').bind(finalData,layer,r.classification,notes,r.id,d.id,r.version,d.id,owner,d.revision));}
   if(b.metadata)statements.push(db.prepare('INSERT INTO edits (id,drawing_id,owner,reason,before_data,after_data,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM drawings WHERE id=? AND owner=? AND revision=?)').bind(id(),d.id,owner,reason,serialized(d.metadata,1000000),serialized(metadata,1000000),time,d.id,owner,d.revision));
   statements.push(db.prepare('UPDATE drawings SET metadata=?,revision=revision+1,reviewed_revision=NULL,updated_at=? WHERE id=? AND owner=? AND revision=?').bind(serialized(metadata,1000000),time,d.id,owner,d.revision));const results=await db.batch(statements);if(results.at(-1).meta.changes!==1)fail(409,'동시 변경이 감지되었습니다. 다시 불러오세요.');return json({revision:d.revision+1});
  }
  if(op==='review'&&request.method==='POST'){
   if(d.status!=='ready')fail(409,'추출 미완료 도면입니다.');const b=await bodyJSON(request);if(b.revision!==d.revision)fail(409,'현재 개정에서 다시 검수하세요.');const qc=inspectDrawing(await allRecords(db,d),d.metadata);if(qc.issues.length)return json({error:'검수 미충족 항목을 먼저 해결하세요.',issues:qc.issues},422);const results=await db.batch([db.prepare('INSERT INTO edits (id,drawing_id,owner,reason,before_data,after_data,created_at) SELECT ?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM drawings WHERE id=? AND owner=? AND revision=?)').bind(id(),d.id,owner,'현재 개정 레이어·BOX·Bay 검수 완료',String(d.reviewed_revision),String(d.revision),now(),d.id,owner,d.revision),db.prepare('UPDATE drawings SET reviewed_revision=? WHERE id=? AND owner=? AND revision=?').bind(d.revision,d.id,owner,d.revision)]);if(!results.at(-1).meta.changes)fail(409,'개정이 바뀌었습니다.');return json({reviewedRevision:d.revision});
  }
  fail(405,'허용하지 않는 요청입니다.');
 }catch(error){if(!error.status)console.error('CAD storage request failed:',error.message);return json({error:error.status?error.message:'저장소 처리 중 오류가 발생했습니다. 입력을 유지한 채 다시 시도하세요.'},error.status||503);}
}};
